export const Avatars = [
    {
        id:1,
        src:"/avatars/Neutral-Profile-Picture-1.png"
    },
    {
        id:2,
        src:"/avatars/Neutral-Profile-Picture-2.png"
    },
    {
        id:3,
        src:"/avatars/Neutral-Profile-Picture-3.png"
    },
    {
        id:4,
        src:"/avatars/Neutral-Profile-Picture-4.png"
    },
    {
        id:5,
        src:"/avatars/Neutral-Profile-Picture-5.png"
    },
    {
        id:6,
        src:"/avatars/Neutral-Profile-Picture-6.png"
    },
    {
        id:7,
        src:"/avatars/Neutral-Profile-Picture-7.png"
    },
    {
        id:8,
        src:"/avatars/Neutral-Profile-Picture-8.png"
    },
    {
        id:9,
        src:"/avatars/Neutral-Profile-Picture-9.png"
    },
    {
        id:10,
        src:"/avatars/Neutral-Profile-Picture-10.png"
    },
    {
        id:11,
        src:"/avatars/Neutral-Profile-Picture-11.png"
    },
    {
        id:12,
        src:"/avatars/Neutral-Profile-Picture-12.png"
    },
    {
        id:13,
        src:"/avatars/Neutral-Profile-Picture-13.png"
    },
    {
        id:14,
        src:"/avatars/Neutral-Profile-Picture-14.png"
    },
    {
        id:15,
        src:"/avatars/Neutral-Profile-Picture-15.png"
    },
    {
        id:16,
        src:"/avatars/Neutral-Profile-Picture-16.png"
    },
    {
        id:17,
        src:"/avatars/Neutral-Profile-Picture-17.png"
    },
    {
        id:18,
        src:"/avatars/Neutral-Profile-Picture-18.png"
    },
    {
        id:19,
        src:"/avatars/Neutral-Profile-Picture-19.png"
    },
    {
        id:20,
        src:"/avatars/Neutral-Profile-Picture-20.png"
    },
    {
        id:21,
        src:"/avatars/Neutral-Profile-Picture-21.png"
    },
    {
        id:22,
        src:"/avatars/Neutral-Profile-Picture-22.png"
    },
    {
        id:23,
        src:"/avatars/Neutral-Profile-Picture-23.png"
    },
    {
        id:24,
        src:"/avatars/Neutral-Profile-Picture-24.png"
    },
    {
        id:25,
        src:"/avatars/Neutral-Profile-Picture-25.png"
    },
    {
        id:26,
        src:"/avatars/Neutral-Profile-Picture-26.png"
    },
    {
        id:27,
        src:"/avatars/Neutral-Profile-Picture-27.png"
    },
    {
        id:28,
        src:"/avatars/Neutral-Profile-Picture-28.png"
    },
    {
        id:29,
        src:"/avatars/Neutral-Profile-Picture-29.png"
    },
    {
        id:30,
        src:"/avatars/Neutral-Profile-Picture-30.png"
    },
    {
        id:31,
        src:"/avatars/Neutral-Profile-Picture-31.png"
    },
    {
        id:32,
        src:"/avatars/Neutral-Profile-Picture-32.png"
    },
    {
        id:33,
        src:"/avatars/Neutral-Profile-Picture-33.png"
    },
    {
        id:34,
        src:"/avatars/Neutral-Profile-Picture-34.png"
    },
    {
        id:35,
        src:"/avatars/Neutral-Profile-Picture-35.png"
    },
    {
        id:36,
        src:"/avatars/Neutral-Profile-Picture-36.png"
    },
    {
        id:37,
        src:"/avatars/Neutral-Profile-Picture-37.png"
    },
    {
        id:38,
        src:"/avatars/Neutral-Profile-Picture-38.png"
    },
    {
        id:39,
        src:"/avatars/Neutral-Profile-Picture-39.png"
    },
    {
        id:40,
        src:"/avatars/Neutral-Profile-Picture-40.png"
    },
    {
        id:41,
        src:"/avatars/Neutral-Profile-Picture-41.png"
    },
    {
        id:42,
        src:"/avatars/Neutral-Profile-Picture-42.png"
    },
    {
        id:43,
        src:"/avatars/Neutral-Profile-Picture-43.png"
    },
    {
        id:44,
        src:"/avatars/Neutral-Profile-Picture-44.png"
    },
    {
        id:45,
        src:"/avatars/Neutral-Profile-Picture-45.png"
    },
    {
        id:46,
        src:"/avatars/Neutral-Profile-Picture-46.png"
    },
    {
        id:47,
        src:"/avatars/Neutral-Profile-Picture-47.png"
    },
    {
        id:48,
        src:"/avatars/Neutral-Profile-Picture-48.png"
    },
    {
        id:49,
        src:"/avatars/Neutral-Profile-Picture-49.png"
    },
    {
        id:50,
        src:"/avatars/Neutral-Profile-Picture-50.png"
    },
    {
        id:51,
        src:"/avatars/Neutral-Profile-Picture-51.png"
    },
    {
        id:52,
        src:"/avatars/Neutral-Profile-Picture-52.png"
    },
    {
        id:53,
        src:"/avatars/Neutral-Profile-Picture-53.png"
    },
    {
        id:54,
        src:"/avatars/Neutral-Profile-Picture-54.png"
    },
    {
        id:55,
        src:"/avatars/Neutral-Profile-Picture-55.png"
    },
    {
        id:56,
        src:"/avatars/Neutral-Profile-Picture-56.png"
    },
    {
        id:57,
        src:"/avatars/Neutral-Profile-Picture-57.png"
    },
    {
        id:58,
        src:"/avatars/Neutral-Profile-Picture-58.png"
    },
]