import { IntroContainer } from "@/container/introduction";
import Layout from "@/container/maincontainer/layout";
import Head from "next/head";

const Intro = () => {
  return (
    <>
      <Head>
        <title>Valentina 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <IntroContainer />
      </Layout>
    </>
  );
};

export default Intro;
